language: java
jdk:
    - oraclejdk8
install: 
    - ant install-maven-dependencies
before-script: 
    - ant -f core/build.xml prepare-test
script: 
    - ant -f core/build.xml test-travis
branches:
    only:
        - master
        - development
cache:
    directories:
    - $HOME/.m2
