language: java
jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7
before-script: 
    - ant -f core/build.xml prepare-test
script: 
    - ant -f core/build.xml test-travis
branches:
    only:
        - master
        - development
cache:
    directories:
    - $HOME/.m2
